// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/messages": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List messages displayed on the quay web app for all user",
                "tags": [
                    "Messages"
                ],
                "summary": "List messages displayed on the quay web app for all user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Dto.Message"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new message to displayed on the quay web app for all user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Create a new message to displayed on the quay web app for all user",
                "parameters": [
                    {
                        "description": "Message content and severity",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Dto.CreateMessage"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Dto.Message"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/messages/{uuid}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a message",
                "tags": [
                    "Messages"
                ],
                "summary": "Delete a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the message to update",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update the content or the severity of an existing message displayed on the quay web app for all user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Update the content or the severity of an existing message displayed on the quay web app for all user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the message to update",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message content and severity",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Dto.UpdateMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Dto.Message"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/organization": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List user's organizations",
                "tags": [
                    "Organization"
                ],
                "summary": "List user's organizations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Dto.Organization"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the current authenticated user information",
                "tags": [
                    "Users"
                ],
                "summary": "Get the current authenticated user information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Dto.UserMeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get the API health status",
                "tags": [
                    "Health"
                ],
                "summary": "Get the API health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Dto.Avatar": {
            "type": "object",
            "properties": {
                "color": {
                    "description": "hex color code",
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "kind": {
                    "description": "e.g., \"user\", \"org\"",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "Dto.CreateMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            }
        },
        "Dto.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "Dto.Organization": {
            "type": "object",
            "properties": {
                "avatar": {
                    "$ref": "#/definitions/Dto.Avatar"
                },
                "can_create_repo": {
                    "type": "boolean"
                },
                "is_org_admin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "preferred_namespace": {
                    "type": "boolean"
                },
                "public": {
                    "type": "boolean"
                }
            }
        },
        "Dto.UpdateMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            }
        },
        "Dto.UserLogin": {
            "type": "object",
            "properties": {
                "metadata": {},
                "service": {
                    "type": "string"
                },
                "service_identifier": {
                    "type": "string"
                }
            }
        },
        "Dto.UserMeResponse": {
            "type": "object",
            "properties": {
                "anonymous": {
                    "type": "boolean"
                },
                "avatar": {
                    "$ref": "#/definitions/Dto.Avatar"
                },
                "can_create_repo": {
                    "type": "boolean"
                },
                "company": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "family_name": {
                    "type": "string"
                },
                "given_name": {
                    "type": "string"
                },
                "has_password_set": {
                    "type": "boolean"
                },
                "invoice_email": {
                    "type": "boolean"
                },
                "invoice_email_address": {
                    "type": "string"
                },
                "is_free_account": {
                    "type": "boolean"
                },
                "is_me": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "logins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Dto.UserLogin"
                    }
                },
                "organizations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Dto.Organization"
                    }
                },
                "preferred_namespace": {
                    "type": "boolean"
                },
                "prompts": {
                    "description": "AI feature in coming ??",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "super_user": {
                    "type": "boolean"
                },
                "tag_expiration_s": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        },
        "Errors.ErrorDetails": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is a sting that represents the error code (e.g. \"USER_NOT_FOUND\", \"INVALID_INPUT\", etc.)",
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "Errors.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/Errors.ErrorDetails"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key authentication using the Authorization header. The value should be in the format \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Quay Go API",
	Description:      "Quay registry API implemented in Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
